name: Run test api

on:
  push:

jobs:
  run-test-api:
    name: Run tests api
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: ls
        run: |
          ls
      - name: Bruno CLI runner
        id: bru-cli
        uses: krummbar/bruno-run-action@main # (1)
        with:
          path: user
          output: output.json
          output-format: json
