name: Run test api

on:
  workflow_dispatch:
    inputs:
      overload_UAT_env:
        type: choice
        description: 'overload testing environement (SIT default)'
        required: false
        options:
          - SIT
          - DEV
          - UAT
  push:

jobs:
  run-test-api:
    name: Run tests api
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Bruno CLI runner
        id: bru-cli
        uses: krummbar/bruno-run-action@main # (1)
        with:
          path: .
          output: output.json
          output-format: json
